### ISSUE TITLE
Addable/deleteable feature for certain brand variables

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/BrandWield-Inc#10]
Just like we did with the people and vehicles in FIS, we want certain variables (and variable sets) to be add-able and delete-able

For example, "people" and "offers" should default to 0, but the use should be able to create as many as they want (of course these new values need to be reflected in the UI as new brand variables, etc etc

**Comment by Rakibuzzaman47** [comment]
Like a "+" or "x" sign to add more info blocks inside Brand area?

**Comment by JakeLabate** [comment]
> Like a "+" or "x" sign to add more info blocks inside Brand area?

Yes. Also - this needs to be tied to firebase, as this is there the data will be stored.
