### ISSUE TITLE
firebase hosting & continual deployment

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/BrandWield-Inc#11]
Ok great - needs to be deployable from WebStorm IDE, a JetBrains web product.

I want to be able to publish site update with the firebase "deploy" feature from the IDE

I have tried it before, I keep getting NPM install related errors. I'm not sure if I have errors in my config files or what the issues is.

I can seem to launch a container successfully, but not deploy the site files to the container.

**Comment by Rakibuzzaman47** [comment]
This seems doable

**Comment by JakeLabate** [comment]
> This seems doable 

Ok great - needs to be deployable from WebStorm IDE, a JetBrains web product.

**Comment by Rakibuzzaman47** [comment]
I believe this one is solved?

**Comment by JakeLabate** [comment]
Nearly

**Comment by JakeLabate** [comment]
using github pages with custom domain of brandwield.com for now
