### ISSUE TITLE
UI Simplicity (Via Field Aggregation)

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/BrandWield-Inc#2]
How do we minimize the amount of STUFF in the UI, while still providing maximum functionality.

Perhaps by using the output fields AS the input fields? Like the output can change around the live input (inline), & based on the input? ...I don't see any reason why not, as long as we clarify THAT is the input field.

Can also type right on the images? (Same principle)

**Comment by Rakibuzzaman47** [comment]
I'll answer tomorrow

**Comment by JakeLabate** [comment]
> I'll answer tomorrow

I am working on this. No need to work on this. Thanks

**Comment by Rakibuzzaman47** [comment]
Ok
