### ISSUE TITLE
Content inside images should be flexible

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/BrandWield-Inc#4]
Objective:
- maintain aesthetic under all possible options

Rules to achieve objective:
- items inside the image divs should take up as much space as possible, but shrink as more content is added... this is a method of portraying a viable image at all (or minimum possible) volumes of content.

**Comment by Rakibuzzaman47** [comment]
I need to check, then I can confirm you how far I can achieve

**Comment by JakeLabate** [comment]
> I need to check, then I can confirm you how far I can achieve 

Ok thank you.

**Comment by JakeLabate** [comment]
other issue #14 included this note
