### ISSUE TITLE
Right click for #brandPopup

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/BrandWield-Inc#5]
update values should be reflected in the right-click menu over the input fields in the "newContent" section (#brandPopup). (Not all brand variable values are currently set up to be accessible here, let's set that up (reference the the variables in firestoreSetup.js that do have this feature. Feel free to refactor as you see fit).

- make a tab/button feature that allows the values visible in the #brandPopup filterable by type (text, image, color, etc). Place these buttons feature below the search bar. Set it up so that the element trigger (the input) selects the relevant filter, by referencing (primarily) the input "type". Refactor as you see fit. Image for reference:
![image](https://user-images.githubusercontent.com/89541068/210127690-adc03dd5-4e1d-44a7-9a2f-921e7a9b2788.jpeg)

**Comment by Rakibuzzaman47** [comment]
Not clear

**Comment by JakeLabate** [comment]
> Not clear

I am able to 'get' the data from firebase based on the specified 'Brand' variable at the top of the firebaseSetup.js file, and then load that data in the 'myBrand' section.

I am also able to 'set' data to firebase within that same .js file.

I have tried several ways to use the 'set' function (a firebase CDN function) to post data back to firebase, but no matter how I try to do it, there is always some error when I try to trigger it from the main.html file... I try setting the function in the .html file, in the .js etc but always get 1 type of error or another.

I don't think I tried using localStorage as a way to transfer data from the .html file to the .js file, maybe this will work? 

Been trying everything on this, can't crack it...

I want when a user 'lock's a variable in the 'my brand' section to trigger setting that input data to firebase.

**Comment by weevil111** [comment]
**Blocker**
I need a list containing mappings from New Content input fields to an array of brand variables that should be shown for that input field

**Comment by weevil111** [comment]
If you search in the brand popup, and select anything from the result (brand recommendations)
Then it does not work
But if you select the same recommendation when the search bar is empty, then it works, i.e. the input field is populated

**Comment by weevil111** [comment]
@JakeLabate  Global update functions (e.g.  _primaryColorGlobalUpdate_, _hookGlobalUpdate_, etc) were not being called if values were chosen from the brand popup. The oninput and onkeyup events are not fired automatically when we change the value of input fields programmatically.
I am fixing this in my PR
