### ISSUE TITLE
Image storage (google storage) for images (not firebase)

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/BrandWield-Inc#6]
An alternative to this maybe me sorting images in firebase in base64 format, seems much much easier at least for now. As long as we can get it working is the goal...

**Comment by Rakibuzzaman47** [comment]
Should be possible, can confirm tomorrow

**Comment by JakeLabate** [comment]
> Should be possible, can confirm tomorrow

An alternative to this maybe me sorting images in firebase in base64 format, seems much much easier at least for now. As long as we can get it working is the goal...

**Comment by JakeLabate** [comment]
We will use base 64
