### ISSUE TITLE
Some function on the 'mybrand' section may be broken

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/BrandWield-Inc#7]
We just need to be sure that these work for all variables:

- load properly from firebase (this includes image formats, stored as base64

- 'clear' buttons work

- 'unlock' buttons work

- 'lock' buttons work

- 'warning' icon shows on no value

- these functions are stored in the myBrand.js file

- note placeholders

**Comment by Rakibuzzaman47** [comment]
I need to give a thorough check tomorrow. Could you share more?

**Comment by JakeLabate** [comment]
> I need to give a thorough check tomorrow. Could you share more?

We just need to be sure that these work for all variables:

- load properly from firebase (this includes image formats, which may best be stored at base64 data? Or maybe the images uploaded to cloud store? Base64 would be much easier for now)

- 'clear' buttons work

- 'unlock' buttons work

- 'lock' buttons work

- these functions are stored in the myBrand.js file
