### ISSUE TITLE
List all [i] items in 1 alert box

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/BrandWield-Inc#9]
I just have to be sure I give those variables the tagged class in all locations that they are in.

As far as displaying them... how can we address this code to make them all appear in 1 alert box?

```js
// list all elements where the class is 'contentVar:Icon'
var elements = document.getElementsByClassName('contentVar:Icon');

// list the value of the title attribute for each parent element of the elements found with the class 'contentVar:Icon', but show them all in 1 alert box
for(var i = 0; i < elements.length; i ++) {
confirm('This change will effect the following ' + elements.length + ' content pieces: ' + elements[i].parentNode.getAttribute('title')); // This creates a new alert box for each item, we want 1 alert box to list ALL .parentNode items.
}
```

**Comment by Rakibuzzaman47** [comment]
Like the primary color changed, then "the code" for primary color should be highlighted?

**Comment by JakeLabate** [comment]
> Like the primary color changes, then "the code" for the primary color should be highlighted? 

I guess document.querySelectorAll('variableNameBeingChanged').forEach => would work, right? As a way to select them?

I just have to be sure I give those variables the tagged class in all locations that they are in.
